catppuccin: dict[str, dict[str, str]] = {
    "accent": {
        "red": "#f38ba8",
        "green": "#a6e3a1",
        "yellow": "#f9e2af",
        "blue": "#89b4fa",
        "purple": "#cba6f7",
        "pink": "#f5c2e7",
        "peach": "#fab387",
        "teal": "#94e2d5",
        "sky": "#89dceb",
        "lavender": "#b4befe",
        "maroon": "#eba0ac",
        "rosewater": "#f5e0dc",
        "flamingo": "#f2cdcd",
        "mauve": "#cba6f7",
        "sapphire": "#74c7ec",
    },
    "text": {
        "primary": "#cdd6f4",
        "secondary": "#bac2de",
        "tertiary": "#a6adc8",
        "disabled": "#7f849c",
    },
    "background": {
        "base": "#1e1e2e",
        "mantle": "#181825",
        "crust": "#11111b",
        "surface0": "#313244",
        "surface1": "#45475a",
        "surface2": "#585b70",
        "overlay0": "#6c7086",
        "overlay1": "#7f849c",
        "overlay2": "#9399b2",
    },
    "status": {
        "success": "#a6e3a1",
        "warning": "#fab387",
        "error": "#f38ba8",
        "info": "#89b4fa",
    },
}
